version: '3.9'

services:
  goldenquizz:
    container_name: goldenquizz
    image: goldenquizz:latest
    build: .
    restart: unless-stopped
    ports:
      - "32777:8080"
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./data:/app/data   # facultatif, si ton app Ã©crit des fichiers
    command: >
      /bin/sh -c "
        echo 'ðŸ”„ Mise Ã  jour du code depuis GitHub...' &&
        git pull origin main || true &&
        uv run python -m goldenquizz.server
      "
